### ISSUE TITLE
Animixed: Top carousel image overflow issue

### ISSUE THREAD

**Issue by KarthikeyaManthri** [xrkaz/personal-stylesheets#5]
![image](https://user-images.githubusercontent.com/30819200/210508054-88ed39ee-5c89-4894-9d20-8880e269e982.png)

I've attached a screenshot of the issue. I love your theme for 9anime by the way. As you can see in the top carousel, for some reason the thumbnail image of the previous carousel item is overflowing to the current item on the left as a thin line. Not a major bug, but will improve the quality of the theme. I can provide additional info if needed. Thanks a lot for this theme!

**Comment by xrkaz** [comment]
Hmm, is this still happening? Can you tell me your display resolution? I'll push an update later today, maybe this will fix it.

**Comment by KarthikeyaManthri** [comment]
Hey, I just checked and yes it is still happening.
![image](https://user-images.githubusercontent.com/30819200/210552448-237446ac-5667-40a4-a662-905222cc2751.png)

My resolution is 1920 x 1080.
When I reduce the zoom of the browser to 90% this issue is not there anymore. So probably it can be an issue with the image width or the carousel item not being scrolled completely.

I tried to check the script myself but unfortunately couldn't figure out the structure. I'm happy to help in any way possible. Thanks a lot!

**Comment by xrkaz** [comment]
I can't seem to reproduce this. How about trying it on a clean browser, Chrome, Firefox, Edge, with Stylus being the only extension enabled?

**Comment by xrkaz** [comment]
Here's the current version btw, if u want to try it out first.
https://privatebin.net/?929358cf64766a4d#F2f22fxwtULxTEk9ZeGGmrNwCDPpUywe3qyvYCd65web

**Comment by KarthikeyaManthri** [comment]
Ah, it's okay then. I tried again with a fresh browser and with only stylus but I still had the issue. For now, I changed the container max-width from 1280px to 1260px and that solved my issue. So I will keep the value in my local from now. Thank you for your amazing work!

**Comment by xrkaz** [comment]
Just added a container width slider to configuration, so that you can still receive updates :)
