### ISSUE TITLE
feature request custom background

### ISSUE THREAD

**Issue by Turhvjbufv** [xrkaz/personal-stylesheets#6]
I would like it to be possible for users to have custom background on 9anime animixplay stylus style, as currently it is not supported v1.0.7
I have checked in the code and it seems there should be an option for that but there is a bug n the code and I am not knowledgeable enough to know how to fix it

**Comment by xrkaz** [comment]
Glad you noticed it :) It's in my todo list, that's why I included it in the code. Will be done in a day or two. Just check for updates in Stylus.

**Comment by xrkaz** [comment]
Just added custom backgrounds. Cheers!
